### ISSUE TITLE
Wrong admin login

### ISSUE THREAD

**Issue by cezarsmpio** [alexcheng1982/docker-magento#21]
Hey Alex, nice work here, congrats!

Well.. I'm trying to login into magento admin panel using my username and password configured on my env variables.

Take a look:
```
environment:
      MYSQL_HOST: magento_db
      MYSQL_DATABASE: magento
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MAGENTO_LOCALE: en_US
      MAGENTO_TIMEZONE: America/Sao_Paulo
      MAGENTO_DEFAULT_CURRENCY: USD
      MAGENTO_ADMIN_USERNAME: ebanx
      MAGENTO_ADMIN_PASSWORD: ebanx123
      MAGENTO_ADMIN_FIRSTNAME: EBANX
      MAGENTO_ADMIN_LASTNAME: Store
      MAGENTO_ADMIN_EMAIL: magento@ebanx.com
      MAGENTO_URL: http://localhost
```

When I go to `http://localhost/admin` and fill with  `ebanx` username and `ebanx123` password, the magento shows `Invalid User Name or Password.`. Why?

![image](https://cloud.githubusercontent.com/assets/954889/26109567/4a3bc9ee-3a26-11e7-9549-38dc517cc361.png)

**Comment by cezarsmpio** [comment]
I tried to search for admin users on database:

```
mysql> select * from admin_user;
Empty set (0.00 sec)
```

The install script may is missing something?

**Comment by cezarsmpio** [comment]
My docker-compose file content:

```
version: '3'

services:
  magento:
    image: alexcheng/magento:latest
    container_name: magento
    ports:
      - 80:80
    links:
      - magento_db
    volumes:
      - ./app/:/var/www/htdocs/app/
      - ./skin/:/var/www/htdocs/skin/
    environment:
      MYSQL_HOST: magento_db
      MYSQL_DATABASE: magento
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MAGENTO_LOCALE: en_US
      MAGENTO_TIMEZONE: America/Sao_Paulo
      MAGENTO_DEFAULT_CURRENCY: USD
      MAGENTO_ADMIN_USERNAME: ebanx
      MAGENTO_ADMIN_PASSWORD: ebanx123
      MAGENTO_ADMIN_FIRSTNAME: EBANX
      MAGENTO_ADMIN_LASTNAME: Store
      MAGENTO_ADMIN_EMAIL: magento@ebanx.com
      MAGENTO_URL: http://localhost

  magento_db:
    image: mariadb:5
    container_name: magento_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    volumes:
      - ./.data:/var/lib/mysql

```
